### ISSUE TITLE
[PSET2] Connection Refused

### ISSUE THREAD

**Issue by LaconicPneumonic** [mit-dci/mas.s62#13]
I'm off campus right now and my connection was refused. Do we have to be on MIT Secure to get and put blocks?

`2018/02/17 12:42:23 dial tcp 18.85.34.200:6262: getsockopt: connection refused`

**Comment by narula** [comment]
Hi Anthony, as the pset says, the server is not up yet.

**Comment by LaconicPneumonic** [comment]
😂 sorry. I should have read more closely.
