### ISSUE TITLE
bitcoind on macOS

### ISSUE THREAD

**Issue by tj-14** [mit-dci/mas.s62#18]
Does the package from https://bitcoincore.org/en/download/ for macOS include bitcoind/bitcoin-cli? If not, should we build from source according to https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md?

**Comment by Varunram** [comment]
@tj-14 download the tar.gz archive for macOS and extract, you should have bitcoin-cli there.

**Comment by josephtchung** [comment]
I think you have to build it for OSX. I have them built and can share if you like. (joe@redstar.com)

**Comment by adiabat** [comment]
you can try to build but it's a pain.  As @Varunram said, it's in the .tar.gz file on bitcoincore.org

**Comment by josephtchung** [comment]
Aha - I didn't notice the tar.gz link before. Yes, much easier.
