### ISSUE TITLE
Have any videos been uploaded?

### ISSUE THREAD

**Issue by moinnadeem** [mit-dci/mas.s62#19]
Hey guys,

Wanted to brush over a few concepts in lecture. Have any of the videos been uploaded?

Thanks!

**Comment by ElasticBottle** [comment]
@moinnadeem @huvegi Not sure if you guys still need the lecture videos, but it seems to be up!

Check it out over [at MIT's OCW website](https://ocw.mit.edu/courses/media-arts-and-sciences/mas-s62-cryptocurrency-engineering-and-design-spring-2018/lecture-videos/)
